// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var containerStyle = {
  display: "flex",
  height: "100%",
  padding: "16px",
  width: "100%",
  alignItems: "center",
  justifyContent: "center"
};

function Container(Props) {
  var children = Props.children;
  return React.createElement("div", {
              style: containerStyle
            }, children);
}

var make = Container;

export {
  containerStyle ,
  make ,
  
}
/* react Not a pure module */
